# -*- coding: utf-8 -*-
"""Global AI Hub Python for Machine Learning Guided Project 1.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-w5iTPJHSnxENL4W3mxnVbDI2CU-K2ic

### Equipment starter pack
The HR department asks you to list the items you would need to improve your work efficiency

Mandatory:
* Laptop
* Headset
* Second monitor

Optional:
* Mousepad
* USB drive
* External drive


📌 Create a shopping list that contains items above and print it.
"""

shopping_list=["laptop","headset","second monitor","mousepad","USB drive","external drive"]

print(shopping_list)

"""####What is mandatory and what is optional?

📌 Use list slicing to devide your list in two list: 'mandatory_item_list' and 'optional_item_list' and print both to the screen.
"""

mandatory_item_list=shopping_list[0:3]

optional_item_list=shopping_list[3:6]

#Print both to the screen
print(mandatory_item_list)
print(optional_item_list)

"""#### Go Shopping
Next, you will have to go and purchase these items, the finance department confirmed a budget of $5000.

📌 Assign 5000 to a variable called limit, so you know how much you can spend.
"""

limit=5000

"""####Price dictionary

Before you start shopping yo need to find the best items that you can buy within the company budget. 

📌 Prepare a dictionary called “price_sheet” that includes the items as keys and the prices as values.  
 
"""

price_sheet={"laptop":1500,
             "headset":100,
             "second monitor":200,
             "mousepad":50,
             "USB drive":70,
             "external drive":250}

"""####Shopping functions

You need to define three functions that will help you during shopping.

📌 First, create an empty list that  will be your shopping cart. Here you will add the items you need to purchase.

1. Define a function for both adding items to the cart and removing them from the item_list.

📌 The "add_to_cart" function should take the item name and the quantity to buy as an argument. 

2. Define a function that will create an invoice. 

📌 The "create_invoice" function should calculate the taxes of each item (18%) and add it to the total amount.

3. Define a function for the checkout. 

📌 The "checkout" function should subtract the total amount from the budget and print a statement to inform if the payment was successful. 
"""

#Initialize the cart list
cart=[]

#Define the "add_to_cart" function
def add_to_cart(item,quantity):
  cart.append=((item,quantity))
  shopping_list.remove=((item))

#Define the "create_invoice" function
def create_invoice():
  total_amount_with_tax=0
  for item,quantity in cart:
    price=price_sheet[item]
    tax = 0.18 * price
    total = ( price + tax ) * quantity
    total_amount_with_tax += total
    return total_amount_with_tax

#Define the "checkout" function
def checkout():
  global limit
  total_amount=create_invoice()
  if limit==0:
    print("you don't have a budget")
  elif total_amount>limit:
    print("you reached your limit. please drop some items.")
  else:
    limit-=total_amount
    print("purchase has been completed successfully.")

"""Let's shop!"""

#Call the "add_to_cart" function for each item
 
#Add first item to cart
add_to_cart("laptop",1)
 
#Add second item to cart
add_to_cart("headset",1)

 
#Add third item to cart
add_to_cart("second monitor",1)

 
#Add fourth item to cart
add_to_cart("mousepad",1)

 
#Add fifth item to cart
add_to_cart("USB drive",1)

 
#Add last item to cart
add_to_cart("external drive",1)

 
#Call the create "checkout" function to pay for all your items 
checkout()