# -*- coding: utf-8 -*-
"""Global AI Hub Python for Machine Learning Guided Project 1.4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-w5iTPJHSnxENL4W3mxnVbDI2CU-K2ic

# Your first task 

Rachel asks you to write a program to track the name and revenue each employee brings.  

* Create the "salesperson_revenue" dictionary to see the employee name as a key and the revenue as a value.

  📌 Every employee starts with 0 revenue.
* Define the "enter_revenue" function. 

  📌 The function takes the name and revenue as an argument and updates the salesperson_revenue dictionary.
"""

#Create salesperson_revenue dictionary
salesperson_revenue={"Ben":0,
"Omer":0,
"Karen":0,
"Bora":0,
"Rose":0
}

#Define enter_revenue function
def enter_revenue(name,revenue):
  global salesperson_revenue
  salesperson_revenue[name]+=revenue

"""####Try out the functions
* In a while loop ask the user to give the name of the employee and for the revenue 

  📌 If the user enters “quit” the loop should break.

After that, print out the salesperson_revenue dictionary.

"""

#Asking user employee name as input
while True:
  name=input("name:")
  if name=="quit":
    break
  revenue=int(input("revenue:"))
  enter_revenue(name,revenue)
  print=(f"{name}'s revenue: {salesperson_revenue[name]}")

#Print the salesperson_revenue dictionary
print(salesperson_revenue)