# -*- coding: utf-8 -*-
"""Global AI Hub Python for Machine Learning Guided Project 1.3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-w5iTPJHSnxENL4W3mxnVbDI2CU-K2ic

###Game Night

You are back at the office and the HR department organizes a welcome party for new employees. 

You decide to create a Rock-Paper-Scissor game. 

📌 Create a Rock-Paper-Scissor game in which the user plays against the computer. The player will choose one of the actions, and the computer will choose its action randomly.
"""

#Import the random library
import random

#create a list containing the three actions of the game.
a_list=['rock','scissors','paper']

#Set the scores of players to 0
player_score=0
pc_score=0

#Ask the user how many rounds they want to play
a=input("How many rounds you wanna play?")

#Add a round_counter that is 0 at the beginning
round_counter=0

#Write a while loop and put the game inside
while True:

  #Increase round_counter by and print it
  round_counter+=1
  print(f"round count:{round_counter}")


  #Select a random action for computer
  computer_choice=random.choice(a_list)

  #Ask player to choose an action
  choice=input("What is your move?")

  #Print the players choices
  print(f"computers choice:{computer_choice} \t player choice:{choice}")



  #tie condition
  if computer_choice==choice:
    print("Tie!")


  #Remaining conditions
  elif computer_choice=='paper':
    if choice=='rock':
      print("computer wins!")
      pc_score+=1
    elif choice=='scissors':
      print("you win!")
      player_score+=1

  elif computer_choice=='rock':
    if choice=='scissors':
      print("computer wins!")
      pc_score+=1
    elif choice=='paper':
      print("you win!")
      player_score+=1

  elif computer_choice=='scissors':
    if choice=='paper':
      print("computer wins!")
      pc_score+=1
    elif choice=='rock':
      print("you win!")
      player_score+=1    
    




  #Stop the while loop if the round_counter equals the number of total rounds
  if a==round_counter:
    break


#Print the outcome of the game by using conditional statements
if pc_score==player_score:
  print("Tie!")

elif pc_score>player_score:
  print("Computer wins!",f"computer score:{pc_score}   player score:{player_score}")

elif pc_score<player_score:
  print("Player wins!",f"player score:{player_score}  computer score:{pc_score},")