# -*- coding: utf-8 -*-
"""Global AI Hub Python for Machine Learning Guided Project 1.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-w5iTPJHSnxENL4W3mxnVbDI2CU-K2ic

# Chapter 1
### Your first day at your new job 👩‍💻👨‍💻

You are starting a new job as a junior software developer in an IT company. 

The company’s HR department asks you to fill out a form, so you start by assigning your personal information to corresponding variables.

📌 Create a variable for your name, surname, age, ID number, place of residence, to specify if you have active health insurance or not, and lastly one for specifying your nationality.
"""

name="Beyda"
surname="Bucak"
age=20
id=1211602099
residence="Edirne"
health_insurance=False
nationality="Turkish"

"""###Meet And Greet
Introduce yourself to your new co-workers.

📌 Use a f-string to introduce yourself.

"""

print(f"My name is {name} {surname}. I am {age} years old and I live in {residence}.")